# Generated by Django 4.0.4 on 2022-05-01 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ib_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_id', models.CharField(max_length=12)),
                ('yesterday', models.DateField()),
                ('ext_id', models.UUIDField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('timezone', models.CharField(max_length=30)),
                ('yesterday_mult', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('access_token', models.CharField(max_length=512)),
                ('refresh_token', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='step_cache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('steps', models.IntegerField()),
                ('ibuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idle_buster.ib_user')),
            ],
        ),
    ]
