# Generated by Django 4.0.4 on 2022-05-20 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idle_buster', '0002_alter_ib_user_access_token_alter_ib_user_ext_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step_cache',
            old_name='created',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='step_cache',
            name='last_updated',
        ),
    ]
